version: '2.3'
services:

  homeassistant:
    image: homeassistant/home-assistant:latest
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/generated:/generated
      #
      # When using docker-ce (or boot2docker) on macOS, you are unable
      # to map the local timezone to your Docker container (Docker issue).
      # Instead of -v /etc/localtime:/etc/localtime:ro, just pass in
      # the timezone environment variable when you launch the container,
      # e.g, -e "TZ=America/Los_Angeles". Replace “America/Los_Angeles”
      # with your timezone.
      # https://www.home-assistant.io/docs/installation/docker/#macos
      #
      # - /etc/localtime:/etc/localtime:ro
      #
    environment:
      - "TZ=Europe/Berlin"
    ports:
      - 8123:8123
    depends_on:
      - mosquitto
    command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-file", "/generated/home-assistant.log" ]
    restart: always

  mosquitto:
    image: toke/mosquitto
    volumes:
      - ./mosquitto/config/:/mqtt/config
      - ./mosquitto/log/:/mqtt/log
      - ./mosquitto/data/:/mqtt/data
    ports:
      - 1883:1883
    restart: always

  appdaemon:
    image: acockburn/appdaemon:latest
    ports:
      - 5050:5050
    volumes:
      - ./appdaemon/config:/conf
    depends_on:
      - homeassistant
    restart: always
